apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: customscaler-v1
spec:
  template:
    spec:
      containers:
      - name: customscaler-v1
        image: testcpa:latest
        imagePullPolicy: IfNotPresent
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testdeployment
  roleRequiresMetricsServer: true
  config:
    - name: interval
      value: "10000"